const FIELD_TYPES = {
  STRING: 'string',
  TEXT: 'text',
  DATE: 'date',
  NUMBER: 'number',
};

const DEFAULT_FIELD_TYPE = FIELD_TYPES.STRING;

const DATE_FORMAT = 'MM/DD/YYYY';

const { STRING: STRING_TYPE, TEXT: TEXT_TYPE, DATE: DATE_TYPE, NUMBER: NUMBER_TYPE } = FIELD_TYPES;
export { STRING_TYPE, TEXT_TYPE, DATE_TYPE, NUMBER_TYPE, DEFAULT_FIELD_TYPE, DATE_FORMAT };
