const FIELD_TYPES = {
  STRING: 'string',
  TEXT: 'text',
  DATE: 'date',
};

const { STRING: STRING_TYPE, TEXT: TEXT_TYPE, DATE: DATE_TYPE } = FIELD_TYPES;

const DATE_FORMAT = 'DD/MMM/YYYY';

export { STRING_TYPE, TEXT_TYPE, DATE_TYPE, DATE_FORMAT };
